### PR TITLE
Added option to change Voice

### PR DESCRIPTION
**Pull request by akshaypx**
Hi Sahil, I found your repo very useful in my own project. And while using it, I found it lacks the option to change voice, but has all the other options present. I have added that option now.

Also added the readme contributors sections. Code formatting has been done by prettier plugin on my end.

### CODE REVIEW

**Comment by SahilAggarwal2004** [comment]
Hi @akshaypx,
Thanks for contributing to this library. I will surely review your pull request today.

**Comment by SahilAggarwal2004** [comment]
Okay, there is a minor problem in setting voice using this approach. The voices array returned by `getVoices()` is browser dependent and there is no guarantee that the number and order of voices will be same for different users using different browsers.
So basically, if someone set the `voice` attribute to 10 (for example). Then there are changes that one person will listen some voice `A` and another person will listen some other voice `B`.

Is there any better solution known to you?

**Comment by akshaypx** [comment]
Okay @SahilAggarwal2004 , thanks for reviewing PR.

I have one more solution, we can provide the `voiceURI` in props which will be a string that contains for example `Microsoft Heera - English (India)` and this string will be checked against `synth.getVoices()` array, if it contains this particular voice string then it will be set else, we can set a default voice.

**Comment by SahilAggarwal2004** [comment]
> Okay @SahilAggarwal2004 , thanks for reviewing PR.
> 
> I have one more solution, we can provide the `voiceURI` in props which will be a string that contains for example `Microsoft Heera - English (India)` and this string will be checked against `synth.getVoices()` array, if it contains this particular voice string then it will be set else, we can set a default voice.

Yeah this solution seems more consistent. Let me implement it and I will push the new version `0.7.0` by today itself.

**Comment by akshaypx** [comment]
> > Okay @SahilAggarwal2004 , thanks for reviewing PR.
> > I have one more solution, we can provide the `voiceURI` in props which will be a string that contains for example `Microsoft Heera - English (India)` and this string will be checked against `synth.getVoices()` array, if it contains this particular voice string then it will be set else, we can set a default voice.
> 
> Yeah this solution seems more consistent. Let me implement it and I will push the new version `0.7.0` by today itself.

I have implemented it, can i add commit to this PR itself?

**Comment by SahilAggarwal2004** [comment]
Yeah sure!

**Comment by SahilAggarwal2004** [comment]
Hey @akshaypx,

I have published the version `0.7.0` with little tweaks. The `voiceURI` attribute can now be an array of strings too, if previous voices are not supported in browser, further voices will be tried! Also, I thought that it will be better to leave the default voice upto the browser only.

Anyways, thanks a lot for your contribution!

**Pull request merged**
